name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies(via npm) for faster builds'
runs:
  using: 'composite'
  steps:
    - name: 'Cache Dependencies'
      uses: 'actions/cache@v3'
      with:
        path: 'node_modules'
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Echo
      run: echo "cache hit ${{ steps.cache-node-modules.outputs.cache-hit }}"

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
