name: Linting, Testing, Building and Deploying

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

  workflow_dispatch:

env:
    GITHUB_BASE_REF: ${{ github.base_ref }}
    GITHUB_HEAD_REF: ${{ github.head_ref }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Get Nx Shas
        uses: nrwl/nx-set-shas@v3


      - name: Run Affected in Pull Request
        if: env.GITHUB_EVENT_NAME == 'pull_request'
        run: |
            npx nx affected:lint --base=origin/${{env.GITHUB_BASE_REF}} --head=origin/${{env.GITHUB_BASE_REF}} --parallel=3

      - name: Run All if not Pull Request
        if: env.GITHUB_EVENT_NAME != 'pull_request'
        run: |
            npx nx lint d-client
            npx nx lint d-server

  Testing:
    needs: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Run Client Unit Tests
        run: npx nx test d-client

      - name: Run Server Unit Tests
        run: npx nx test d-server

      - name: Run Server Integration Tests
        run: npx nx test:int d-server

