name: Linting, Testing, Building and Deploying

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

  workflow_dispatch:

env:
    GITHUB_BASE_REF: ${{ github.base_ref }}
    GITHUB_HEAD_REF: ${{ github.head_ref }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Get Nx Shas
        uses: nrwl/nx-set-shas@v3
        # NX_BASE and NX_HEAD environment variables will be set in this Job

      - name: Run Affected Lint in Pull Request Event
        if: env.GITHUB_EVENT_NAME == 'pull_request'
        run: npx nx affected -t lint --base=origin/${{env.GITHUB_BASE_REF}} --head=origin/${{env.GITHUB_HEAD_REF}} --parallel=3

      - name: Run All Lints in other Events
        if: env.GITHUB_EVENT_NAME != 'pull_request'
        run: npx nx affected -t lint --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}} --parallel=3

  Testing:
    needs: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Get Nx Shas
        uses: nrwl/nx-set-shas@v3
        # NX_BASE and NX_HEAD environment variables will be set in this Job

      - name: Run Affected Unit Tests in Pull Request Event
        if: env.GITHUB_EVENT_NAME == 'pull_request'
        run: npx nx affected -t test --base=origin/${{env.GITHUB_BASE_REF}} --head=origin/${{env.GITHUB_HEAD_REF}} --parallel=3

      - name: Run Affected Integration Tests in Pull Request Event
        if: env.GITHUB_EVENT_NAME == 'pull_request'
        run: npx nx affected -t test:int --base=origin/${{env.GITHUB_BASE_REF}} --head=origin/${{env.GITHUB_HEAD_REF}} --parallel=3

      - name: Run All Unit Tests in other Events
        if: env.GITHUB_EVENT_NAME != 'pull_request'
        run: npx nx affected -t test --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}} --parallel=3

      - name: Run All Integration Tests in other Events
        if: env.GITHUB_EVENT_NAME != 'pull_request'
        run: npx nx affected -t test:int --base=${{env.NX_BASE}} --head=${{env.NX_HEAD}} --parallel=3


