name: Linting, Testing, Building and Deploying

on:
  pull_request:
    branches:
      - main
      - development

  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Run Affected in Pull Request
        uses: nrwl/nx-set-shas@v3
        if: ${{ github.event_name == 'pull_request' }}
    #   - run: npx nx format:check

      - name: Run Affected in Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
            npx nx affected:lint --base=origin/${{github.base_ref}} --head=origin/${{github.head_ref}} --parallel=3

      - name: Run All if not Pull Request
        if: ${{ github.event_name != 'pull_request' }}
        run: |
            npx nx lint d-client
            npx nx lint d-server

  Testing:
    needs: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Run Client Unit Tests
        run: npx nx test d-client

      - name: Run Server Unit Tests
        run: npx nx test d-server

      - name: Run Server Integration Tests
        run: npx nx test:int d-server

