name: Linting, Testing, Building and Deploying

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: test
        run: echo "${{ toJSON(github.repositoryUrl) }} test"

    #   - name: Load & Cache Dependencies
    #     uses: ./.github/actions/cached-deps

    #   - name: Lint Client
    #     run: npx nx lint d-client

    #   - name: Lint Server
    #     run: npx nx lint d-server

#   Testing:
#     needs: Linting
#     runs-on: ubuntu-latest

#     steps:
#       - name: Get Code
#         uses: actions/checkout@v3

#       - name: Load & Cache Dependencies
#         uses: ./.github/actions/cached-deps

#       - name: Run Client Unit Tests
#         run: npx nx test d-client

#       - name: Run Server Unit Tests
#         run: npx nx test d-server

#       - name: Run Server Integration Tests
#         run: npx nx test:int d-server

